### ISSUE TITLE
at.h

### ISSUE THREAD

**Issue by willrogers** [willrogers/at#13]
@lfarv would prefer the integrators not to depend on `at.h`.

Can you just clarify what the purpose of `at.h` is?  Is it for the matlab side?

I don't want to duplicate definitions.  I think it would be neatest if we could handle most of the platform incompatibilities in one file that everything can include.  But I am not an expert in laying out C code.

**Comment by lfarv** [comment]
In our setup, at.h was used in "old style" integrators, using the "passFunction" entry and not suitable for Python access. When we converted the 1st integrator, we removed all "mx" reference in the integrator itself, implemented the "trackFunction" entry and provided the "atelem.c" header instead of "at.h" to handle platform or language differences. So "atelem.c" should be the only necessary header in "new style" integrators. "at.h" was modified not to block compilation without Matlab by translating most mx... calls, however the resulting integrator cannot be used in pyat since in misses the right entry point. And it appears that there are still some exotic mx... or mex... references in some integrators to be removed in the future.

**Comment by willrogers** [comment]
Does this mean we will be able to remove `at.h`?

**Comment by lfarv** [comment]
No, because AT users may have developed their own integrators, and they have to continue running ! Matlab still support both integrator types !

**Comment by willrogers** [comment]
Sure.  Some comments might help clarify this.

Could `at.h` and `atelem.c` share any common code?

**Comment by lfarv** [comment]
They do. Is it worth creating another header to factorise that ? I don't know... It's up to you

**Comment by willrogers** [comment]
This is now refactored to handle both old and new build methods.
